DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
    id INT PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    username VARCHAR(64),
    role VARCHAR(20) NOT NULL,
    passwordhash BLOB NOT NULL,
    passwordsalt BLOB NOT NULL
);

DROP TABLE IF EXISTS SPACE;

CREATE TABLE SPACE (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    userid INT,
    FOREIGN KEY (userid) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TASKLIST (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    spaceid INT,
    FOREIGN KEY (spaceid) REFERENCES SPACE(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS TASK;

CREATE TABLE TASK (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(64) NOT NULL,
    description VARCHAR(264) NOT NULL,
    tasklistid INT,
    status BOOLEAN NOT NULL,
    FOREIGN KEY (tasklistid) REFERENCES TASKLIST(id) ON DELETE CASCADE ON UPDATE CASCADE
);